### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by MartinKavik** [TatriX/play-with-me-seed#1]
Hi!
Live demo doesn't work. (Windows 10, Firefox & Chrome)
1. https://tatrix.org/public/games/play-with-me/
1. `Create/connect`
1. I see `loading...`  and in console log:
```
`WebAssembly.instantiateStreaming` failed. Assuming this is because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 TypeError: "Response has unsupported MIME type"
```

---

Maybe this can help: https://github.com/David-OConnor/seed/pull/184/files

**Comment by TatriX** [comment]
Oups. The issue was with server VM changing IP. Should be fixes now.
